apiVersion: v1 
kind: Pod 
metadata:
 name: demo-pod-port
 labels:
  name: demo-app-port
  tier: app
spec:
 containers: 
 - name: demo-app-port-container
   image: nginx
   ports:
     - containerPort: 80