apiVersion: v1
kind: Pod
metadata:
  name: demo-secret-env-var-pod
spec:
  containers:
    - name: demo-secret-env-var-pod-container
      image: busybox
      command: [ 'sh', '-c', 'echo Database Password: $DATABASE_PASSWORD & sleep 3600' ]
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: databasePassword