apiVersion: v1 
kind: Pod 
metadata:
 name: demo-security-context-pod
 labels:
  name: demo-app
  tier: app
spec:
 securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
 volumes:
    - name: sec-context-volume
      emptyDir: {}
 containers: 
 - name: demo-sec-context-app-container
   image: busybox 
   command: [ "sh", "-c", "sleep 3600" ] 
   volumeMounts:
     - name: sec-context-volume
       mountPath: /data/demo
