apiVersion: v1
kind: Pod
metadata:
  name: demo-readiness-probe-healthy
spec:
  containers:
    - name: demo-readiness-probe-container
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3